name: waste_management_app
description: LiftAway - Fast. Simple. Reliable Waste Removal
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  fl_chart: ^0.63.0
  image_picker: ^1.0.8
  image_picker_for_web: ^3.0.2
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  smooth_page_indicator: ^1.1.0
  animations: ^2.0.8
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  file_picker: ^10.3.7
  flutter_tts: ^4.2.0
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/
